name: polars_dart
repository: https://github.com/Desdaemon/polars_dart
packages:
  - packages/**
  - scripts

commands:
  bootstrap:
    hooks:
      post: cargo check --manifest-path polars-wrapper/Cargo.toml
  clean:
    hooks:
      pre: cargo clean --manifest-path polars-wrapper/Cargo.toml
  version:
    hooks:
      preCommit: bash scripts/version.sh

scripts:
  # only MacOS machines (CI or otherwise) can realistically invoke this.
  build:
    melos run build-apple &&
    melos run build-android &&
    melos run build-other

  # the only time 'melos run build-*' is called is to prepare
  # for distribution, so use the 'min' profile.
  build-apple: dart scripts/build_apple.dart --profile min
  build-android: bash scripts/build-android.sh --profile min
  build-other: dart scripts/build_other.dart --profile min

  # Platform-specific builds, mainly for testing
  build-ios: dart scripts/build_apple.dart --ios
  build-macos: dart scripts/build_apple.dart --local
  build-other-local: dart scripts/build_other.dart --local

  test:
    cargo build --release &&
    melos run test-dart &&
    melos run test-flutter
  
  test-dart:
    exec: dart test -x bench
    packageFilters:
      flutter: false
      dirExists: test
    # select-package:

  test-flutter:
    exec: flutter test integration_test
    packageFilters:
      flutter: true
      dirExists: integration_test

  bench:
    exec: dart test -t bench
    packageFilters:
      flutter: false
      dirExists: test/bench

  analyze:
    exec: flutter analyze .
    description: Analyze a specific package in this project.

  check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.

  format:
    exec: dart format .
    description: Format a specific package in this project.

  # TODO: deprecate when first version to pub.dev is published
  docs:
    exec: dart doc -o ../../website/\$MELOS_PACKAGE_NAME
    packageFilters:
      private: false
