name: polars_dart
description: Dart bindings to the polars library
version: 0.1.0
homepage: https://www.pola.rs
repository: https://github.com/Desdaemon/polars_dart

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  # TODO(Desdaemon): Build WASM library
  # web:

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.2.0
  ffigen: ^7.2.4
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.59.0
  meta: ^1.8.0
