name: polars
description: Dart bindings to the polars library
version: 0.1.0
homepage: https://www.pola.rs
repository: https://github.com/Desdaemon/polars_dart

platforms:
  macos:
  linux:
  windows:
  android:
  ios:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  benchmark_harness: ^2.2.0
  build_runner: ^2.3.3
  ffigen: ">=8.0.0 <10.0.0"
  freezed: ^2.3.2
  lints: ">=2.0.0 <4.0.0"
  path: ^1.8.3
  test: ^1.16.0
dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: 2.0.0-dev.9
  freezed_annotation: ^2.2.0
  meta: ^1.8.0
