[package]
name = "polars-wrapper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
chrono-tz = "0.8.1"
flutter_rust_bridge = "1.59.0"

[dependencies.polars]
version = "0.26.1"
default-features = false
features = ["csv-file", "lazy", "abs", "cum_agg", "product", "describe"]

[profile.release]
lto = "thin"
strip = "debuginfo"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false # wasm-opt doesn't work
