frb_bin := "cargo run --manifest-path ~/flutter_rust_bridge/frb_codegen/Cargo.toml --"
# frb_bin := "flutter_rust_bridge_codegen"

gen:
	{{frb_bin}}	\
		-r src/wrapper.rs \
		--rust-output src/bridge.rs \
		-d ../packages/polars/lib/src/wrapper.dart \
		-c include/polars_wrapper.h \
		--no-use-bridge-in-method

check: gen
	cargo check
