frb_bin := "cargo run --manifest-path ~/flutter_rust_bridge/frb_codegen/Cargo.toml -- generate"
# frb_bin := "flutter_rust_bridge_codegen generate"

gen:
	{{frb_bin}}	\
		-r src/wrapper.rs \
		--rust-output src/bridge.rs \
		-d ../packages/polars/lib/src/wrapper \
		-c include/polars_wrapper.h \
		--no-web \
		--dump-all

check: gen
	cargo check
